import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { siteSettingsApi } from '@/services/siteSettings';

const blank = { enabled: false, accountNumber: '', accountName: '', instructions: '' };
export default function PaymentSettings() {
  const [settings, setSettings] = useState({ jazzCash: blank, easypaisa: blank }); const [advance, setAdvance] = useState(20);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(null);
  useEffect(() => { siteSettingsApi.getPaymentSettings().then((data) => { setSettings({ jazzCash: { ...blank, ...data.paymentSettings.jazzCash }, easypaisa: { ...blank, ...data.paymentSettings.easypaisa } }); setAdvance(data.codAdvancePercentage || 20); }).catch((err) => toast.error(err.response?.data?.message || 'Could not load payment settings')).finally(() => setLoading(false)); }, []);
  const update = (key, field, value) => setSettings((current) => ({ ...current, [key]: { ...current[key], [field]: value } }));
  const save = async (key) => { setSaving(key); try { const data = await siteSettingsApi.updatePaymentSettings({ [key]: settings[key] }); setSettings((current) => ({ ...current, [key]: data[key] })); toast.success(`${key === 'jazzCash' ? 'JazzCash' : 'Easypaisa'} settings saved`); } catch (err) { toast.error(err.response?.data?.message || 'Could not save payment settings'); } finally { setSaving(null); } };
  const saveAdvance = async () => { setSaving('advance'); try { const value = await siteSettingsApi.saveCodAdvancePercentage(Number(advance)); setAdvance(value); toast.success('COD advance setting saved'); } catch (err) { toast.error(err.response?.data?.message || 'Could not save COD advance setting'); } finally { setSaving(null); } };
  if (loading) return <p className="text-ivory/50">Loading payment settings…</p>;
  return <div className="max-w-3xl space-y-8"><div><p className="eyebrow mb-2">Store configuration</p><h1 className="heading-display text-3xl">Payment Settings</h1><p className="text-sm text-ivory/55 mt-2">Manage online payment options and the COD advance required at checkout.</p></div><section className="glass p-6 space-y-4"><h2 className="font-display text-2xl">COD Advance Percentage</h2><p className="text-sm text-ivory/60">Customers pay this portion online before their Cash on Delivery order is confirmed.</p><select value={advance} onChange={(e) => setAdvance(Number(e.target.value))} className="bg-obsidian border border-gold/25 px-4 py-3 text-sm"><option value={10}>10%</option><option value={20}>20%</option></select><button onClick={saveAdvance} disabled={saving === 'advance'} className="block px-6 py-2.5 bg-gold text-obsidian text-xs tracking-widest2 uppercase font-semibold">{saving === 'advance' ? 'Saving…' : 'Save COD Advance'}</button></section><WalletCard title="JazzCash" config={settings.jazzCash} onChange={(field, value) => update('jazzCash', field, value)} onSave={() => save('jazzCash')} saving={saving === 'jazzCash'} /><WalletCard title="Easypaisa" config={settings.easypaisa} onChange={(field, value) => update('easypaisa', field, value)} onSave={() => save('easypaisa')} saving={saving === 'easypaisa'} /></div>;
}
function WalletCard({ title, config, onChange, onSave, saving }) { return <section className="glass p-6 space-y-5"><div className="flex items-center justify-between gap-4"><h2 className="font-display text-2xl">{title}</h2><label className="flex items-center gap-2 text-sm text-ivory/70 cursor-pointer"><input type="checkbox" checked={config.enabled} onChange={(e) => onChange('enabled', e.target.checked)} className="accent-gold w-4 h-4" /> Enabled</label></div><Input label="Account / Wallet Number" value={config.accountNumber} onChange={(e) => onChange('accountNumber', e.target.value)} required={config.enabled} /><Input label="Account Holder Name (optional)" value={config.accountName} onChange={(e) => onChange('accountName', e.target.value)} /><div><label className="block text-[11px] tracking-widest2 uppercase text-ivory/50 mb-2">Payment Instructions (optional)</label><textarea value={config.instructions} onChange={(e) => onChange('instructions', e.target.value)} maxLength={600} rows={3} className="w-full bg-transparent border border-gold/25 px-4 py-2.5 text-sm focus:outline-none focus:border-gold resize-y" /></div><button onClick={onSave} disabled={saving} className="px-6 py-2.5 bg-gold text-obsidian text-xs tracking-widest2 uppercase font-semibold disabled:opacity-50">{saving ? 'Saving…' : `Save ${title} Settings`}</button></section>; }
function Input({ label, required, ...props }) { return <div><label className="block text-[11px] tracking-widest2 uppercase text-ivory/50 mb-2">{label}</label><input {...props} required={required} maxLength={120} className="w-full bg-transparent border border-gold/25 px-4 py-2.5 text-sm focus:outline-none focus:border-gold" /></div>; }
